# ALERT: This compose file is only for testing

version: "1.0"
name: biokb_chebi_test

services:
  pma:
    image: docker.io/phpmyadmin/phpmyadmin:5.2.1
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  mysql:
    image: docker.io/library/mysql:8.4.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: biokb_chebi
      MYSQL_USER: biokb_chebi_user
      MYSQL_PASSWORD: biokb_chebi_password
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

  neo4j:
    image: docker.io/library/neo4j:5.20.0
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4j_password

